import item1 from '../Images/item1.jpg';
import item2 from '../Images/item2.jpg';
import item3 from '../Images/item3.jpg';
import item4 from '../Images/item4.jpg';
import item5 from '../Images/item5.jpg';
import item6 from '../Images/item6.jpg';
import item7 from '../Images/item7.jpg';

export const ITEMS = [
    {
        item_id: 1,
        item_name: 'Rose Garden Bouquet',
        item_description: 'A delightful arrangement of fresh roses in various colors.',
        item_price: 49.99,
        item_discount: 5,
        item_rating: 4.7,
        item_image: item1,
        item_category: 'Flower Bouquets',
        item_color: 'Various',
        item_size: 'Standard',
        item_material: 'Fresh Roses',
        item_brand: 'Blossom Bliss',
        item_stock: 25,
    },
    {
        item_id: 2,
        item_name: 'Lavender Fields Bouquet',
        item_description: 'Experience the calming essence of lavender with this enchanting bouquet.',
        item_price: 39.99,
        item_discount: 0,
        item_rating: 4.8,
        item_image: item2,
        item_category: 'Flower Bouquets',
        item_color: 'Purple',
        item_size: 'Standard',
        item_material: 'Fresh Lavender',
        item_brand: 'Scented Serenity',
        item_stock: 30,
    },
    {
        item_id: 3,
        item_name: 'Sunflower Surprise Bouquet',
        item_description: 'Brighten someone\'s day with this cheerful arrangement of sunflowers.',
        item_price: 44.99,
        item_discount: 10,
        item_rating: 4.5,
        item_image: item3,
        item_category: 'Flower Bouquets',
        item_color: 'Yellow',
        item_size: 'Standard',
        item_material: 'Fresh Sunflowers',
        item_brand: 'Sunshine Delight',
        item_stock: 20,
    },
    {
        item_id: 4,
        item_name: 'Tulip Dream Bouquet',
        item_description: 'Elegant tulips in an assortment of colors, perfect for any occasion.',
        item_price: 59.99,
        item_discount: 15,
        item_rating: 4.6,
        item_image: item4,
        item_category: 'Flower Bouquets',
        item_color: 'Various',
        item_size: 'Standard',
        item_material: 'Fresh Tulips',
        item_brand: 'Tulip Treasures',
        item_stock: 18,
    },
    {
        item_id: 5,
        item_name: 'Orchid Elegance Bouquet',
        item_description: 'Exquisite orchids arranged beautifully to convey sophistication.',
        item_price: 79.99,
        item_discount: 0,
        item_rating: 4.9,
        item_image: item5,
        item_category: 'Flower Bouquets',
        item_color: 'White/Pink',
        item_size: 'Standard',
        item_material: 'Fresh Orchids',
        item_brand: 'Orchid Oasis',
        item_stock: 15,
    },
    {
        item_id: 6,
        item_name: 'Daisy Delight Bouquet',
        item_description: 'A charming bouquet featuring cheerful daisies to spread happiness.',
        item_price: 34.99,
        item_discount: 5,
        item_rating: 4.4,
        item_image: item6,
        item_category: 'Flower Bouquets',
        item_color: 'White/Yellow',
        item_size: 'Standard',
        item_material: 'Fresh Daisies',
        item_brand: 'Daisy Days',
        item_stock: 22,
    },
    {
        item_id: 7,
        item_name: 'Peony Paradise Bouquet',
        item_description: 'Indulge in luxury with these opulent peonies, a symbol of prosperity.',
        item_price: 89.99,
        item_discount: 0,
        item_rating: 4.7,
        item_image: item7,
        item_category: 'Flower Bouquets',
        item_color: 'Pink',
        item_size: 'Standard',
        item_material: 'Fresh Peonies',
        item_brand: 'Peony Palace',
        item_stock: 12,
    },
    {
        item_id: 8,
        item_name: 'Carnation Carnival Bouquet',
        item_description: 'A vibrant medley of carnations bursting with color and energy.',
        item_price: 29.99,
        item_discount: 10,
        item_rating: 4.3,
        item_image: item2,
        item_category: 'Flower Bouquets',
        item_color: 'Various',
        item_size: 'Standard',
        item_material: 'Fresh Carnations',
        item_brand: 'Carnation Creations',
        item_stock: 28,
    },
    {
        item_id: 9,
        item_name: 'Hydrangea Harmony Bouquet',
        item_description: 'Experience tranquility with this captivating arrangement of hydrangeas.',
        item_price: 49.99,
        item_discount: 5,
        item_rating: 4.6,
        item_image: item3,
        item_category: 'Flower Bouquets',
        item_color: 'Blue/Pink',
        item_size: 'Standard',
        item_material: 'Fresh Hydrangeas',
        item_brand: 'Hydrangea Haven',
        item_stock: 20,
    },
    {
        item_id: 10,
        item_name: 'Wildflower Wonder Bouquet',
        item_description: 'Celebrate nature\'s beauty with a mix of vibrant wildflowers.',
        item_price: 39.99,
        item_discount: 0,
        item_rating: 4.5,
        item_image: item1,
        item_category: 'Flower Bouquets',
        item_color: 'Various',
        item_size: 'Standard',
        item_material: 'Fresh Wildflowers',
        item_brand: 'Wildflower Whimsy',
        item_stock: 25,
    },
];
